<div class="row">
	<div class="large-4 columns">
		Kyle W. Rader
		<br><br>
		WWU ACM Activities Coordinator<br>
		Director of Engineering: <a href="https://secure.agiplanner.com">AgiPlanner</a>
	</div>
		<div class="large-4 large-offset-4 columns">
		Checkout this website's source code!
		<br><br>
		<a href="https://github.com/kyle-rader/cs.mcyamaha.com"><i class="fi-social-github" style="font-size:50pt;"></i></a>
	</div>
</div>
<script>
$(document).foundation();
</script>