<div class="row">
	<div class="large-4 columns">
		Kyle W. Rader
		<br><br>
		WWU ACM Activities Coordinator<br>
		Director of Engineering: <a href="https://secure.agiplanner.com">AgiPlanner</a>
	</div>
		<div class="large-3 large-offset-5 columns">
		<ul class="icon-group">
			<li><a href="mailto:kyle.rader@ieee.org"><i class="fi-mail"></i></a></li>
			<li><a href="https://www.linkedin.com/pub/kyle-rader/7b/361/882"><i class="fi-social-linkedin"></i></a></li>
			<li><a href="https://github.com/kyle-rader/cs.mcyamaha.com"><i class="fi-social-github"></i></a></li>
		</ul>
	</div>
</div>
<script>
$(document).foundation();
</script>