<div class="fixed">
	<nav class="top-bar" data-topbar>

	  <section class="top-bar-section">
		<!-- Right Nav Section -->
		<ul class="right">
		  <li class="has-dropdown">
			<a href="#">Resources</a>
			<ul class="dropdown">
			  <li><a href="http://www.reddit.com/r/web_design/">r/ Web Design</a></li>
			  <li><a href="http://www.reddit.com/r/webdev">r/ Web Dev</a></li>
			</ul>
		  </li>
		  <li class="has-dropdown">
			<a href="#">CS@WWU</a>
			<ul class="dropdown">
			  <li><a href="#">First link in dropdown</a></li>
			</ul>
		  </li>
		</ul>

		<!-- Left Nav Section -->
		<ul class="left">
		  <li><a href="/">Home</a></li>
		  <li class="has-dropdown">
			<a href="#">TA Classes</a>
			<ul class="dropdown">
			  <li><a href="#">CSCI 145</a></li>
			</ul>
		  </li>
		  <li><a href="#">IceBreaker</a></li>
		</ul>
	  </section>
	</nav>
</div>