<?php

print <<<EOT
<head>
	<title>$page_title</title>
	<meta charset="UTF-8">
	<link rel="icon" type="image/png" href="/img/favicon.ico">
	<script src="/foundation/js/jquery.js"></script>
	<script src="/foundation/js/modernizr.js"></script>
	<script src="/foundation/js/foundation.min.js"></script>
	<script src="/foundation/js/vendor/fastclick.js"></script>
	<script src="/foundation/js/jquery.md5.js"></script>
	<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" href="/foundation/css/foundation.min.css">
	<link rel="stylesheet" type="text/css" href="/foundation/css/normalize.css">
	<link rel="stylesheet" type="text/css" href="/foundation-icons/foundation-icons.css">
	<link rel="stylesheet" type="text/css" href="/foundation/css/custom.css">
</head>
EOT;
?>
