<?php

print <<<EOT
<head>
	<title>$page_title</title>
	<meta charset="UTF-8">
	<script src="/foundation/js/jquery.js"></script>
	<script src="/foundation/js/modernizr.js"></script>
	<script src="/foundation/js/foundation.min.js"></script>
	<script src="/foundation/js/vendor/fastclick.js"></script>
	<link rel="stylesheet" type="text/css" href="/foundation/css/custom.css">
	<link rel="stylesheet" type="text/css" href="/foundation/css/foundation.min.css">
	<link rel="stylesheet" type="text/css" href="/foundation/css/normalize.css">
	<link rel="stylesheet" type="text/css" href="/foundation/css/custom.css">
</head>
EOT;
?>
