<div class="fixed">
	<nav class="top-bar" data-topbar>

		<section class="top-bar-section">
			<!-- Right Nav Section -->
			<ul class="right">
				<li class="has-dropdown">
					<a href="">Funny Things</a>
					<ul class="dropdown">
						<li><a target=_blank href="http://www.reddit.com/r/techsupportgore">r/ Tech Support Gore</a></li>
						<li><a target=_blank href="http://programmerryangosling.tumblr.com/">Programming Pick-up Lines</a></li>
						<li><a target=_blank href="http://www.eecis.udel.edu/~zurawski/humor/new_os_air.html">OS Airlines</a></li>
						<li><a target=_blank href="http://users.cms.caltech.edu/~mvanier/hacking/rants/cars.html">OS Cars</a></li>
						<li class="has-dropdown">
							<a href="">Videos</a>
							<ul class="dropdown">
								<li><a target=_blank href="https://www.youtube.com/watch?v=rT1nGjGM2p8">Key & Peel East/West Bowl 2</a></li>
								<li><a target=_blank href="http://www.youtube.com/watch?v=_uScCrpAW4U">Key & Peel Secret Agent</a></li>
							</ul>
						</li>
					</ul>
				</li>
				<li class="has-dropdown">
					<a href="">Resources</a>
					<ul class="dropdown">
						<li><a target=_blank href="http://www.tutorialspoint.com/computer_programming/index.htm">Tutorials Point</a></li>
						<li><a target=_blank href="http://stackoverflow.com">Stack Overflow</a></li>
						<li><a target=_blank href="http://www.codecademy.com/">Code Academy</a></li>
						<li><a target=_blank href="http://foundation.zurb.com/">Zurb Foundation</a></li>
						<li><a target=_blank href="http://www.reddit.com/r/web_design/">r/ Web Design</a></li>
						<li><a target=_blank href="http://www.reddit.com/r/webdev">r/ Web Dev</a></li>
					</ul>
				</li>
				<li class="has-dropdown">
					<a href="">CS @ WWU</a>
					<ul class="dropdown">
						<li><a target=_blank href="https://cst.wwu.edu/computer-science">WWU CS Home</a></li>
						<li><a target=_blank href="http://support.cs.wwu.edu/index.php/Main_Page">CS Support</a></li>
						<li><a target=_blank href="http://sw.cs.wwu.edu/~nordwap/index.php">Web Cams</a></li>
						<li><a target=_blank href="http://sw.cs.wwu.edu/~fugiera/dev/labStat2.php">Lab Stats</a></li>
						<li><a target=_blank href="http://acm.wwu.edu/">ACM</a></li>
						<li><a target=_blank href="http://awc.cs.wwu.edu/">AWC</a></li>
					</ul>
				</li>
			</ul>

			<!-- Left Nav Section -->
			<ul class="left">
				<li class="active"><a class="top-btn" data-target="home">Home</a></li>
				<li><a class="top-btn" data-target="bio">About</a></li>
				<li class="has-dropdown">
					<a href="#">TA Classes</a>
					<ul class="dropdown">
						<li><a class="top-btn" data-target="cs145">CSCI 145</a></li>
					</ul>
				</li>
				<li><a class="top-btn" data-target="videos">Videos</a></li>
				<li><a href="http://bio.mcyamaha.com">BioInformatics</a></li>
			</ul>
		</section>
	</nav>
</div>